CREATE TABLE BOOK (
  ID INT AUTO_INCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  PAGES INT NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL
);

--INSERT INTO BOOK (TITLE, PAGES, AUTHOR) VALUES ('SPRING IN ACTION', 100, 'DAN VEGA');
--INSERT INTO BOOK (TITLE, PAGES, AUTHOR) VALUES ('ANGULAR IN ACTION', 150, 'VINAYAK JONDHALE');
--INSERT INTO BOOK (TITLE, PAGES, AUTHOR) VALUES ('KAFKA BASICS', 200, 'POOJA PUJI');