CREATE TABLE BOOK (
  ID INT AUTO_INCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  PAGES INT NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  CREATE_TS TIMESTAMP
);

CREATE TABLE ADDRESS(
    ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    STREET1 VARCHAR(250) NOT NULL,
    STREET2 VARCHAR(250) NOT NULL
);

CREATE TABLE USERS(
    USER_ID INT AUTO_INCREMENT,
    NAME VARCHAR(250) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE FILE(
    ID VARCHAR(250),
    NAME VARCHAR(250) NOT NULL,
    TYPE VARCHAR(250),
    DATA BLOB
);


